import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import { headers } from 'next/headers';
import { cookieToInitialState } from 'wagmi';
import { config } from '@/config';
import Web3ModalProvider from './WalletProvider';

import StoreProvider from "@/app/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Connect Wallet Page",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const initialState = cookieToInitialState(config, headers().get('cookie'))
    
    return (
        <html lang="en">
            <body className={inter.className}>
                <Web3ModalProvider initialState={initialState}>
                    <StoreProvider>
                        {children}
                    </StoreProvider>
                </Web3ModalProvider>
            </body>
        </html>
    );
}
