import type { Metadata } from "next";

import { headers } from 'next/headers';
import { cookieToInitialState } from 'wagmi';
import { config } from '@/config';
import Web3ModalProvider from './WalletProvider';

import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header/Header";
import Banner from "@/components/Banner/Banner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vortex NFT market place",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3ModalProvider initialState={initialState}>
          <Header />
          <Banner />
          {children}
        </Web3ModalProvider>
      </body>
    </html>
  );
}
