import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header/Header";
import Banner from "@/components/Banner/Banner";

import StoreProvider from "../StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vortex NFT market place",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Header />
          <Banner />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
